active_store : "faiss"

faiss:
  index_path: "faiss_local_index"

chroma:
  persist_directory: "chroma_local_index"
  collection_name: "deepcrawl_collection"

quadrant:
  persist_directory: "quadrant_local_index"
  collection_name: "deepcrawl_collection"
  metadata_fields:
    - "url"
    - "content"
    - "timestamp"
    - "source"
