defaults:
  - _self_
  - database: default
  - vectorstore: default
  - llm: google
  - embedding: default
  - worker: default


app:
  name: "DeepCrawl Chat"
  version: "1.0.1"
  log_dir: "logs"
  environment: ${oc.env:ENVIRONMENT,development}
  debug: ${oc.env:DEBUG,false}

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

redis:
  host: "localhost"
  port: 6379
  db: 0
  password: null
  pool_size: 10